### ISSUE TITLE
Support default locale

### ISSUE THREAD

**Issue by marvinmarnold** [marvinmarnold/textit_chat#11]
We should be able to define a default locale such that when that is the current, no parameters are appended to the url. To do that, I think the application controller, default_url_options just needs to be modified to not append anything if the current locale is the default locale.

**Comment by mikevallano** [comment]
I'm a bit stumped on this one. I tried:
  def default_url_options(options={})
    { :locale => ((I18n.locale == "en") ? nil : I18n.locale) }
  end

But it is not working. 

I'll hold off as you might be able to do it in 5 minutes, or we can discuss when we get together next.

**Comment by marvinmarnold** [comment]
Was a little trickier than I thought. A few edge cases. I think I fixed it in this commit 67322ac

**Comment by mikevallano** [comment]
Nice solution!
