### ISSUE TITLE
Refactor locale selector in forms

### ISSUE THREAD

**Issue by marvinmarnold** [marvinmarnold/textit_chat#12]
There is some duplication of code in the forms for the locale selection. There are a few ways this could be handled. One possibility is using (the built in Rails dropdown helpers)[http://guides.rubyonrails.org/form_helpers.html#select-boxes-for-dealing-with-models]. Gotta run now, so details may be off, but it involves changing:

  <div class="form-group">
    <p>Select Language</p>
    <select name="consultation_question[locale]">
      <option value="en">English</option>
      <option value="zu">Zulu</option>
      <option value="xh">Xhosa</option>
    </select>
  </div>

TO

in views:

<div class="form-group">
    <%= f.label :locale, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :locale, locale_array, class: "form-control" %>
    </div>

  </div>

in application_hepler:
def locale_array
 [["English", "en"], ["Spanish", "es"], ...]
end

**Comment by mikevallano** [comment]
Awesome refactor. I was wondering how to do that in a DRY way without having a Locale model. Implemented in this PR: https://github.com/marvinmarnold/textit_chat/pull/14
