### ISSUE TITLE
Locale availability in views

### ISSUE THREAD

**Issue by marvinmarnold** [marvinmarnold/textit_chat#6]
@mikevallano there are a few models (Faqs, Consultations, HealthProblem, etc) that now have an extra `locale` attribute (6ba88a2ce67def3951fe51edb97fe28ba02db227). But when you go to [/faqs/new](http://localhost:3000/faqs/new?locale=en), you can't specify which locale you are doing that for. The same applies for editing and viewing all those objects. By preloading the DB with some entities from the seeds files you improved, we haven't been dependent on views to make object.

**Comment by marvinmarnold** [comment]
And the input type for the locale should probably be a dropdown. This would be a hardcoded list of countries we currently support. Eventually, that list could be autopopulated based off of the presence of different files like en.anything.yml. But that's prob overkill right now.

**Comment by mikevallano** [comment]
Created pull request https://github.com/marvinmarnold/textit_chat/pull/10
