### ISSUE TITLE
Add language picker dropdown to nav

### ISSUE THREAD

**Issue by mikevallano** [marvinmarnold/textit_chat#7]

**Comment by mikevallano** [comment]
Review proposal doc for list of supported languages

**Comment by mikevallano** [comment]
According to the doc, there isn't a final list of languages, but it seems the top three would be Zulu, Xhosa and English

**Comment by marvinmarnold** [comment]
Ya that sounds right. I have no clue what the two character abbreviation for those may be but they should be defined in a standard somewhere.

**Comment by mikevallano** [comment]
After some research, Rails only supports 27 locales by default, and Zulu and Xhosa aren't in the list. However, apparently you can just add those locales as yaml files in the locales folder and then it works. I was getting an error regarding unrecognized locale, but now it's working. 

Pull request: https://github.com/marvinmarnold/textit_chat/pull/9
